### ISSUE TITLE
Document: How to use with Istio

### ISSUE THREAD

**Issue by haf-afa** [redboxllc/scuttle#10]
These env vars:

```
        env:
        - name: ISTIO_QUIT_API
          value: http://127.0.0.1:15020
        - name: ENVOY_ADMIN_API 
          value: http://127.0.0.1:15000
```

works on istio 1.3.3

**Comment by ptzianos** [comment]
Isn't this covered in the `1.3 and higher` section of the README?

**Comment by gracezhucl** [comment]
Hi team, may I ask other than adding in environment vars like this:
```
env:
            - name: ENVOY_ADMIN_API
              value: http://127.0.0.1:15000
            - name: SCUTTLE_LOGGING
              value: "true"
            - name: ISTIO_QUIT_API
              value: http://127.0.0.1:15020
```
Anything else I need to add to make scuttle stop istio? Since right now I dont see it is stopping istio and I dont see any logs. Thank you!!
