### ISSUE TITLE
Consider using Istio readiness check instead of Envoy admin API

### ISSUE THREAD

**Issue by linjmeyer** [redboxllc/scuttle#35]
Current the `ENVOY_ADMIN_API` is used to prevent application startup until Istio/Envoy is ready.  Istio itself has a readiness probe (used by k8s healthchecks) at `http://127.0.0.1:15020/healthz/ready`.  Looking at the master branch of Istio this endpoint verifies the Istio Admin API is ready (or it will time out), and internally verifies Envoy is operational.

I think using Istio's readiness endpoint makes more sense as we can be more confident that not only Envoy is ready, but Istio itself is too.  Most likely this would mean deprecating `ENVOY_ADMIN_API` as the name of the variable wouldn't make sense.

**Comment by JoeJasinski** [comment]
Hey @linjmeyer, I tried setting the `ENVOY_ADMIN_API` to `http://127.0.0.1:15020/healthz/ready` with an existing release of scuttle, scuttle seems to start up, and envoy reports it is ready, but the main pod never seems to get started and the pod hangs forever. I've separately curled the  `http://127.0.0.1:15020/healthz/ready` url and it returns a 200 when the pod is ready. 

Here is where scuttle starts up:
```
curlpod-2 curlpod-container-jjj 2021-04-10T00:52:33Z scuttle: Scuttle 1.3.1 starting up, pid 1
curlpod-2 curlpod-container-jjj 2021-04-10T00:52:33Z scuttle: Logging is now enabled
curlpod-2 curlpod-container-jjj 2021-04-10T00:52:33Z scuttle: Blocking until Envoy starts
```

Here the last thing that gets logged.. envoy is ready. But the main workload never runs.

```
curlpod-2 istio-proxy 2021-04-10T00:52:36.397354Z       info    Envoy proxy is ready
```

And here is the pod

```
command:
- scuttle
- bash
- -cx
- --
- curl -v http://myservice:8000/api/
env:
- name: ENVOY_ADMIN_API
  value: http://127.0.0.1:15020/healthz/ready
- name: ISTIO_QUIT_API
  value: http://127.0.0.1:15000
```

Does scuttle need to be changed to account for the different url?
