### ISSUE TITLE
Propagate container failure to pod status

### ISSUE THREAD

**Issue by yanasega** [redboxllc/scuttle#43]
We have a pod that runs tests (main container) and an istio sidecar. Once scuttle is added to the flow, even if the test container has failed tests, the entire pod enters 'Completed' state as appose to an 'Error' state (which occurs if scuttle is not present).
Is it possible to propagate the status of the failed test container to the pod?
e.g
```
NAME    READY   STATUS      RESTARTS   AGE
test      0/2           Error                  0          38m
```
and not:
```
NAME     READY   STATUS      RESTARTS   AGE
test           0/2      Completed             0          38m
```

error as seen in pod:
```
  containerStatuses:
  - containerID: docker://...
    image: istio/proxyv2:1.5.8
    name: istio-proxy
    state:
      terminated:
        containerID: docker://...
        exitCode: 0
        finishedAt: "2021-01-19T09:36:40Z"
        reason: Completed
        startedAt: "2021-01-19T09:07:19Z"
  - containerID: docker://...
    name: test
    state:
      terminated:
        containerID: docker://...
        exitCode: 120
        finishedAt: "2021-01-19T09:36:40Z"
        reason: Error
        startedAt: "2021-01-19T09:07:19Z"
```
lean pod yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    sidecar.istio.io/inject: "true"
  restartPolicy: Never
  containers:
    - name: test
      command: ["scuttle", "/bin/sh", "-c"] 
     env:
        - name: ENVOY_ADMIN_API
          value: "http://127.0.0.1:15000"
        - name: ISTIO_QUIT_API
          value: "http://127.0.0.1:15000"
```

**Comment by linjmeyer** [comment]
Hi @yanasega!  Scuttle takes the exit code from your app (tests in this case), based on what you provided that did happen and the exit code was 120:

```
- containerID: docker://...
    name: test
    state:
      terminated:
        containerID: docker://...
        exitCode: 120
        finishedAt: "2021-01-19T09:36:40Z"
        reason: Error
        startedAt: "2021-01-19T09:07:19Z"
```

I know if a single container fails in a Job or CronJob Kubernetes considers this a failure.  We use Scuttle the same as you describe to run integration tests, when the tests (a Job) fails our pipelines halt the deployment.  How are you running this pod?  Is it controlled by another resource type (Job, Deployment, etc.)?

**Comment by yanasega** [comment]
Hi @linjmeyer thanks for the quick replay!
We are running it as a single pod without deployment/Job. I do see that the error code is propagated, but the pod still enters a 'Completed' state:

> 2021-01-20T09:06:01Z scuttle: Kill received: (Action: Stopping Istio with API, Reason: ISTIO_QUIT_API is set, Exit Code: 120)
2021-01-20T09:06:01Z scuttle: Stopping Istio using Istio API 'http://127.0.0.1:15000' (intended for Istio >v1.2)
2021-01-20T09:06:01Z scuttle: Received signal 'child exited', passing to child
2021-01-20T09:06:01Z scuttle: Received signal 'urgent I/O condition', passing to child
2021-01-20T09:06:01Z scuttle: Sent quitquitquit to Istio, status code: 200

**Comment by linjmeyer** [comment]
I dug into this a bit, [the field on the pod that Kubernetes will set when a container fails is ](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase)`phase`.  When 1 or more container fails the phase will be `phase: failed`.  For example, here is a pod with Scuttle that failed tests:

```
apiVersion: v1
kind: Pod
metadata:
  // ...
  name: example
  namespace: example
spec:
  containers:
  - // ..container (failed tests)
  - // ..container (istio sidecar)
status:
  conditions: // ...
  containerStatuses // ... 
  phase: Failed # <-- this is the field you want to watch
```

I'm not sure why `kubectl` doesn't show that, but I think Scuttle is working as expected.  Can you double check the `phase` field on the pods?
